name: 签到

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 0,12 * * * # At 00:00 and 12:00, every day
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 运行脚本
      env:
        WYY_USER:  ${{ secrets.USER }}
        WYY_PWD: ${{ secrets.PWD }}
        SERVER_SCK: ${{ secrets.SCK }}
      run: |
        pip install -r requirements.txt
        python3 checkin.py

