name: 签到

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 0,12 * * * # At 00:00 and 12:00, every day
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - if: ${{ secrets.SCK }} == ""
      name: 签到不发送消息
      run: |
        pip install -r requirements.txt
        
        python3 checkin.py ${{ secrets.USER }} ${{ secrets.PWD }}

    - if: ${{ secrets.SCK }} != ""
      name: 签到并发送消息
      run: |
        pip install -r requirements.txt
        
        python3 checkin.py ${{ secrets.USER }} ${{ secrets.PWD }} ${{ secrets.SCK }}